baseURL = "https://notes.dmaitre.phyip3.dur.ac.uk/computing-club/"
publishDir = "public/computing-club"
languageCode = "en-gb"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  # contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    languageName = "English"
    title = "Computing Club"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Computing Club"
      logoHomeLink = ""

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "sessions"
        name = "Sessions"
        url = "/posts"
